"""add videos segments styles

Revision ID: e7f874937cf2
Revises: fede7b49c8db
Create Date: 2025-12-23 09:27:03.229052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7f874937cf2'
down_revision: Union[str, Sequence[str], None] = 'fede7b49c8db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segments',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.CheckConstraint('start < "end"', name='ck_segment_start_lt_end'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('video_id', 'id'),
    sa.UniqueConstraint('video_id', 'id', name='uq_segment_video_id')
    )
    op.create_table('styles',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('style_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.add_column('videos', sa.Column('owner_key', sa.String(), nullable=False))
    op.add_column('videos', sa.Column('burned_uri', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('videos', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_videos_owner_key'), 'videos', ['owner_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_owner_key'), table_name='videos')
    op.drop_column('videos', 'updated_at')
    op.drop_column('videos', 'created_at')
    op.drop_column('videos', 'burned_uri')
    op.drop_column('videos', 'owner_key')
    op.drop_table('styles')
    op.drop_table('segments')
    # ### end Alembic commands ###
